[W 151208 07:45:23 web:1908] 405 GET /create_group (127.0.0.1) 0.75ms
[I 151208 07:45:42 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:45:44 web:1908] 200 GET /create_group (127.0.0.1) 1.18ms
[I 151208 07:46:01 web:1908] 200 GET /create_group?owner=919999823930 (127.0.0.1) 0.56ms
[I 151208 07:47:06 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:47:08 web:1908] 304 GET /create_group?owner=919999823930 (127.0.0.1) 1.12ms
[I 151208 07:47:16 web:1908] 304 GET /create_group?owner=919999823930 (127.0.0.1) 0.43ms
[I 151208 07:47:30 web:1908] 304 GET /create_group?owner=919999823930 (127.0.0.1) 0.72ms
[I 151208 07:48:01 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:48:07 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:48:19 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:48:27 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:48:35 web:1908] 200 GET /create_group?owner=919999823930 (127.0.0.1) 1.17ms
[I 151208 07:49:16 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:49:20 web:1908] 304 GET /create_group?owner=919999823930 (127.0.0.1) 0.75ms
[I 151208 07:49:40 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:49:46 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:49:51 web:1908] 304 GET /create_group?owner=919999823930 (127.0.0.1) 1.08ms
[I 151208 07:50:08 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:50:12 autoreload:204] group_chat.py modified; restarting server
[I 151208 07:50:16 web:1908] 200 GET /create_group?owner=919999823930 (127.0.0.1) 0.89ms
[I 151208 07:50:35 web:1908] 200 GET /create_group?owner=919999823930&name=group1 (127.0.0.1) 0.66ms
[I 151208 07:51:18 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875] (127.0.0.1) 16.80ms
[I 151208 07:52:27 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875] (127.0.0.1) 9.90ms
[I 151208 11:06:11 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:06:27 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:06:36 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875] (127.0.0.1) 15.19ms
[I 151208 11:06:49 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[%2791854329875%27] (127.0.0.1) 13.48ms
[I 151208 11:07:38 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:07:58 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:08:04 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[%2791854329875%27] (127.0.0.1) 14.90ms
[I 151208 11:09:21 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:09:24 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[%2791854329875%27] (127.0.0.1) 12.19ms
[I 151208 11:09:54 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:10:01 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[%2791854329875%27] (127.0.0.1) 11.71ms
[I 151208 11:10:50 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:10:55 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[%2791854329875%27] (127.0.0.1) 2.24ms
[I 151208 11:11:09 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:11:14 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[%2791854329875%27] (127.0.0.1) 10.39ms
[I 151208 11:11:33 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875] (127.0.0.1) 8.77ms
[I 151208 11:12:03 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:12:18 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:12:22 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875] (127.0.0.1) 1.24ms
[I 151208 11:12:38 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:13:17 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:13:22 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875] (127.0.0.1) 9.71ms
[I 151208 11:13:37 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:13:55 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:14:49 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:14:58 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:15:01 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875] (127.0.0.1) 14.93ms
[I 151208 11:15:21 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:15:24 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:15:27 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:15:32 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875] (127.0.0.1) 14.83ms
[I 151208 11:15:59 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,%20910564327612] (127.0.0.1) 13.29ms
[I 151208 11:16:13 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 13.44ms
[I 151208 11:16:49 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:17:06 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:18:03 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:18:17 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:18:44 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:19:16 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 19.52ms
[I 151208 11:20:26 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:20:34 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:20:57 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:21:03 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:21:09 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 15.04ms
[I 151208 11:21:58 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:22:14 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:22:19 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 13.17ms
[I 151208 11:22:34 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:22:40 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:22:58 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:23:00 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:23:05 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:23:09 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:23:13 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:23:25 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 17.17ms
[I 151208 11:24:28 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:24:44 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 18.62ms
[I 151208 11:25:12 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:25:32 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 17.62ms
[I 151208 11:27:09 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:27:53 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 18.31ms
[I 151208 11:31:45 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:32:18 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:32:23 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 20.61ms
[I 151208 11:32:33 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:33:04 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/db_handler.py modified; restarting server
[I 151208 11:33:11 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 22.09ms
[I 151208 11:33:37 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:33:41 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 18.75ms
[I 151208 11:34:46 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:35:04 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 24.73ms
[I 151208 11:35:29 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:37:05 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 19.13ms
[I 151208 11:37:28 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:37:32 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 40.19ms
[I 151208 11:38:07 autoreload:204] group_chat.py modified; restarting server
[I 151208 11:38:17 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 48.58ms
[I 151208 15:21:42 web:1908] 200 GET /get_groups (127.0.0.1) 14.43ms
[I 151208 15:22:00 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:22:03 web:1908] 200 GET /get_groups (127.0.0.1) 1.07ms
[I 151208 15:22:10 web:1908] 304 GET /get_groups (127.0.0.1) 0.72ms
[I 151208 15:22:12 web:1908] 304 GET /get_groups (127.0.0.1) 0.71ms
[I 151208 15:22:33 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:22:48 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:23:00 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:23:02 web:1908] 200 GET /get_groups (127.0.0.1) 10.65ms
[I 151208 15:23:13 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:23:16 web:1908] 200 GET /get_groups (127.0.0.1) 0.73ms
[I 151208 15:23:35 web:1908] 200 GET /get_groups?user=91999982393 (127.0.0.1) 9.51ms
[E 151208 15:23:39 web:1496] Uncaught exception GET /get_groups?user=919999823930 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/get_groups?user=919999823930', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 197, in get
        self.write(response)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 697, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 88, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: datetime.datetime(2015, 12, 8, 11, 38, 17, 714962) is not JSON serializable
[E 151208 15:23:39 web:1908] 500 GET /get_groups?user=919999823930 (127.0.0.1) 54.07ms
[I 151208 15:24:29 autoreload:204] group_chat.py modified; restarting server
[E 151208 15:24:32 web:1496] Uncaught exception GET /get_groups?user=919999823930 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/get_groups?user=919999823930', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 198, in get
        self.write(response)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 697, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 88, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: datetime.datetime(2015, 12, 8, 11, 38, 17, 714962) is not JSON serializable
[E 151208 15:24:32 web:1908] 500 GET /get_groups?user=919999823930 (127.0.0.1) 33.93ms
[I 151208 15:24:39 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:24:52 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:24:59 autoreload:204] group_chat.py modified; restarting server
[E 151208 15:25:02 web:1496] Uncaught exception GET /get_groups?user=919999823930 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/get_groups?user=919999823930', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Cache-Control': 'max-age=0', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 198, in get
        self.write(response)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 697, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 88, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: datetime.datetime(2015, 12, 8, 11, 38, 17, 714962) is not JSON serializable
[E 151208 15:25:02 web:1908] 500 GET /get_groups?user=919999823930 (127.0.0.1) 40.94ms
[I 151208 15:25:24 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:25:28 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:25:38 autoreload:204] group_chat.py modified; restarting server
[E 151208 15:25:41 web:1496] Uncaught exception GET /get_groups?user=919999823930 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/get_groups?user=919999823930', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 199, in get
        return self.write(response)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 697, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 88, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: datetime.datetime(2015, 12, 8, 11, 38, 17, 714962) is not JSON serializable
[E 151208 15:25:41 web:1908] 500 GET /get_groups?user=919999823930 (127.0.0.1) 29.46ms
[I 151208 15:25:57 autoreload:204] group_chat.py modified; restarting server
[E 151208 15:26:02 web:1496] Uncaught exception GET /get_groups?user=919999823930 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/get_groups?user=919999823930', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 199, in get
        return self.write(response)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 697, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 88, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: datetime.datetime(2015, 12, 8, 11, 38, 17, 714962) is not JSON serializable
[E 151208 15:26:02 web:1908] 500 GET /get_groups?user=919999823930 (127.0.0.1) 28.60ms
[I 151208 15:26:44 autoreload:204] group_chat.py modified; restarting server
[E 151208 15:26:47 web:1496] Uncaught exception GET /get_groups?user=919999823930 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/get_groups?user=919999823930', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Cache-Control': 'max-age=0', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 200, in get
        return self.write(response)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 697, in write
        chunk = escape.json_encode(chunk)
      File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 88, in json_encode
        return json.dumps(value).replace("</", "<\\/")
      File "/usr/lib/python2.7/json/__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "/usr/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
      File "/usr/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: datetime.datetime(2015, 12, 8, 11, 38, 17, 714962) is not JSON serializable
[E 151208 15:26:47 web:1908] 500 GET /get_groups?user=919999823930 (127.0.0.1) 33.48ms
[I 151208 15:27:14 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:27:26 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 27.34ms
[I 151208 15:28:25 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:28:38 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:28:42 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:29:00 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:29:07 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:29:22 autoreload:204] group_chat.py modified; restarting server
[I 151208 15:29:32 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 26.54ms
[I 151208 15:51:38 autoreload:204] group_chat.py modified; restarting server
[W 151208 15:51:57 web:1908] 405 GET /create_group (127.0.0.1) 0.50ms
[W 151208 15:54:16 web:1908] 405 GET /create_group?method=POST (127.0.0.1) 0.36ms
[I 151208 16:00:55 autoreload:204] group_chat.py modified; restarting server
[I 151208 16:02:41 autoreload:204] group_chat.py modified; restarting server
[I 151208 16:03:09 autoreload:204] group_chat.py modified; restarting server
[I 151208 16:03:36 autoreload:204] group_chat.py modified; restarting server
[I 151208 16:03:56 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:08:35 web:1908] 200 GET /create_group (127.0.0.1) 9.86ms
[I 151209 13:10:01 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:10:07 web:1908] 304 GET /create_group (127.0.0.1) 10.49ms
[I 151209 13:10:20 web:1908] 304 GET /create_group?owner=919999823930 (127.0.0.1) 10.20ms
[I 151209 13:10:28 web:1908] 200 GET /create_group?owner=919999823930&name=group1 (127.0.0.1) 9.66ms
[I 151209 13:11:15 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:11:20 web:1908] 304 GET /create_group?owner=919999823930&name=group1 (127.0.0.1) 10.29ms
[I 151209 13:12:38 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:12:43 web:1908] 200 GET /create_group?owner=919999823930&name=group1 (127.0.0.1) 1.26ms
[I 151209 13:13:00 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[91854329875,910564327612] (127.0.0.1) 10.05ms
[I 151209 13:13:36 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[919716671667,%20919958776104] (127.0.0.1) 12.09ms
[I 151209 13:14:30 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:14:33 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[919716671667,%20919958776104] (127.0.0.1) 16.89ms
[I 151209 13:15:27 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:15:58 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[919716671667,919958776104] (127.0.0.1) 12.13ms
[I 151209 13:17:24 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:17:38 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:17:43 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[919716671667,919958776104] (127.0.0.1) 10.05ms
[I 151209 13:18:13 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:18:27 web:1908] 304 GET /create_group?owner=919999823930&name=group1&members=[919716671667,919958776104] (127.0.0.1) 12.73ms
[I 151209 13:19:20 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:20:20 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:20:26 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[919716671667,919958776104] (127.0.0.1) 87.88ms
[I 151209 13:28:00 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[919716671667,919958776104] (127.0.0.1) 58.30ms
[I 151209 13:28:44 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:28:49 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:28:59 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:29:36 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[919716671667,919958776104] (127.0.0.1) 53.63ms
[I 151209 13:30:12 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:30:40 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:30:58 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[919716671667,919958776104] (127.0.0.1) 53.18ms
[I 151209 13:31:10 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:31:35 web:1908] 200 GET /create_group?owner=919999823930&name=group1&members=[919716671667,919958776104] (127.0.0.1) 88.82ms
[I 151209 13:34:08 web:1908] 200 GET /send_message (127.0.0.1) 0.70ms
[I 151209 13:34:40 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:34:49 web:1908] 304 GET /send_message (127.0.0.1) 1.11ms
[I 151209 13:35:06 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:35:17 web:1908] 200 GET /send_message (127.0.0.1) 10.53ms
[I 151209 13:36:49 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:36:55 web:1908] 304 GET /send_message (127.0.0.1) 10.36ms
[I 151209 13:37:23 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:37:27 web:1908] 304 GET /send_message (127.0.0.1) 13.79ms
[I 151209 13:37:56 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:37:58 web:1908] 304 GET /send_message (127.0.0.1) 22.24ms
[I 151209 13:38:08 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:38:22 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:38:24 web:1908] 200 GET /send_message (127.0.0.1) 1.38ms
[I 151209 13:38:37 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:39:15 web:1908] 200 GET /send_message?sender=919958776104&group_name=group1 (127.0.0.1) 1.19ms
[I 151209 13:39:19 web:1908] 200 GET /send_message?sender=919958776104&group_name=group2 (127.0.0.1) 0.57ms
[I 151209 13:39:27 web:1908] 304 GET /send_message?sender=919958776104&group_name=group2 (127.0.0.1) 0.59ms
[I 151209 13:40:08 autoreload:204] group_chat.py modified; restarting server
[I 151209 13:40:27 web:1908] 304 GET /send_message?sender=919958776104&group_name=group2 (127.0.0.1) 0.74ms
[I 151209 13:50:34 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:04:30 web:1908] 304 GET /send_message?sender=919958776104&group_name=group2 (127.0.0.1) 0.93ms
[I 151209 14:04:55 web:1908] 200 GET /send_message?sender=919958776104&group_name=group2&message=hello (127.0.0.1) 18.54ms
[I 151209 14:05:08 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:05:12 web:1908] 200 GET /send_message?sender=919958776104&group_name=group2&message=hello (127.0.0.1) 26.06ms
[I 151209 14:05:36 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:05:39 web:1908] 200 GET /send_message?sender=919958776104&group_name=group2&message=hello (127.0.0.1) 27.42ms
[I 151209 14:05:45 web:1908] 200 GET /send_message?sender=919958776179&group_name=group2&message=hello (127.0.0.1) 8.96ms
[I 151209 14:05:51 web:1908] 304 GET /send_message?sender=919958776104&group_name=group2&message=hello (127.0.0.1) 19.00ms
[I 151209 14:05:55 web:1908] 200 GET /send_message?sender=919958776104&group_name=group1&message=hello (127.0.0.1) 30.34ms
[I 151209 14:06:53 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:07:09 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:08:22 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/errors.py modified; restarting server
[I 151209 14:12:16 web:1908] 200 GET /get_groups (127.0.0.1) 0.69ms
[I 151209 14:13:08 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:13:11 web:1908] 304 GET /get_groups (127.0.0.1) 0.83ms
[I 151209 14:13:29 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:13:32 web:1908] 200 GET /get_groups (127.0.0.1) 12.53ms
[I 151209 14:13:37 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:13:43 autoreload:204] group_chat.py modified; restarting server
[E 151209 14:13:48 web:1496] Uncaught exception GET /get_groups (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/get_groups', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'If-None-Match': '"aa166fc12c08e3dd25005e6bd5c4676a2271a5e8"', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1417, in _execute
        raise TypeError("Expected None, got %r" % result)
    TypeError: Expected None, got {'info': "Please provide user's contact number", 'status': 400}
[E 151209 14:13:48 web:1908] 500 GET /get_groups (127.0.0.1) 1.55ms
[I 151209 14:14:04 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:14:08 web:1908] 200 GET /get_groups (127.0.0.1) 2.04ms
[I 151209 14:14:17 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 0.45ms
[I 151209 14:14:42 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:14:46 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 9.88ms
[I 151209 14:15:50 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:15:55 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:16:16 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:16:29 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:16:34 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 13.55ms
[I 151209 14:16:54 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:16:56 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 21.06ms
[I 151209 14:17:04 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:17:17 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:17:23 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:17:29 web:1908] 304 GET /get_groups?user=919999823930 (127.0.0.1) 17.32ms
[I 151209 14:17:55 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:17:57 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 17.43ms
[I 151209 14:18:16 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:18:19 web:1908] 304 GET /get_groups?user=919999823930 (127.0.0.1) 10.01ms
[I 151209 14:18:32 autoreload:204] group_chat.py modified; restarting server
[I 151209 14:18:36 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 25.23ms
[I 151209 14:20:29 web:1908] 200 GET /create_group?owner=919958776104&name=group1&members=[91854329875,910564327612] (127.0.0.1) 8.98ms
[I 151209 14:21:14 web:1908] 200 GET /create_group?owner=919958776104&name=group1&members=[919716671667,919999823930] (127.0.0.1) 85.75ms
[I 151209 14:22:20 web:1908] 200 GET /create_group?owner=919958776104&name=group2&members=[919716671667,919999823930] (127.0.0.1) 74.08ms
[I 151209 14:22:47 web:1908] 200 GET /send_message?sender=919811389321 (127.0.0.1) 0.57ms
[I 151209 14:23:49 web:1908] 200 GET /send_message?sender=919811389321&group_name=group1&message=200 (127.0.0.1) 19.13ms
[I 151209 14:24:41 web:1908] 200 GET /send_message?sender=919958776104&group_name=group1&message=200 (127.0.0.1) 28.19ms
[I 151209 14:27:27 web:1908] 200 GET /get_groups?user=919999823930 (127.0.0.1) 35.10ms
[I 151209 14:28:18 web:1908] 200 GET /create_group?owner=919811389321&name=group3&members=[919999823930] (127.0.0.1) 76.07ms
[I 151209 14:28:45 web:1908] 200 GET /send_message?sender=919958776104&group_name=group2 (127.0.0.1) 0.54ms
[I 151209 14:29:01 web:1908] 200 GET /send_message?sender=919811389321&group_name=group4 (127.0.0.1) 0.47ms
[I 151209 14:29:15 web:1908] 200 GET /send_message?sender=919811389321&group_name=group4&message=how%20%20are%20you (127.0.0.1) 23.23ms
[I 151209 14:29:22 web:1908] 200 GET /send_message?sender=919811389321&group_name=group3&message=how%20%20are%20you (127.0.0.1) 34.79ms
[I 151209 14:29:56 web:1908] 200 GET /send_message?sender=919811389321&group_name=group3&message=how+are+you (127.0.0.1) 28.08ms
[I 151209 14:30:24 web:1908] 200 GET /send_message?sender=919811389321&group_name=group3&message=how (127.0.0.1) 35.17ms
[I 151209 14:32:57 web:1908] 304 GET /send_message?sender=919811389321&group_name=group3&message=how (127.0.0.1) 35.92ms
[I 151209 14:33:38 web:1908] 200 GET /send_message?sender=919999823930&group_name=group3&message=yayeee (127.0.0.1) 28.13ms
[I 151209 14:36:48 web:1908] 304 GET /create_group?owner=919811389321&name=group3&members=[919999823930] (127.0.0.1) 69.89ms
[I 151209 14:37:21 web:1908] 200 GET /send_message?sender=919811389321&group_name=group3&message=heheh (127.0.0.1) 29.01ms
[I 151209 14:40:16 web:1908] 304 GET /create_group?owner=919811389321&name=group3&members=[919999823930] (127.0.0.1) 85.88ms
[I 151209 14:40:47 web:1908] 200 GET /send_message?sender=919811389321&group_name=group3 (127.0.0.1) 0.72ms
[I 151209 14:40:51 web:1908] 304 GET /send_message?sender=919811389321&group_name=group3&message=how (127.0.0.1) 28.43ms
[I 151209 14:45:00 web:1908] 304 GET /create_group?owner=919811389321&name=group3&members=[919999823930] (127.0.0.1) 81.32ms
[I 151209 14:45:29 web:1908] 304 GET /send_message?sender=919811389321&group_name=group3 (127.0.0.1) 1.68ms
[I 151209 14:45:40 web:1908] 200 GET /send_message?sender=919811389321&group_name=group3&message=how=aakarshi (127.0.0.1) 33.65ms
[I 151209 14:46:35 web:1908] 200 GET /get_groups?user=919811389321 (127.0.0.1) 44.10ms
[I 151209 14:58:39 web:1908] 304 GET /send_message?sender=919811389321&group_name=group3&message=how (127.0.0.1) 32.19ms
[I 151209 15:05:21 web:1908] 200 GET /create_group?owner=919811389321&name=group4&members=[919999823930] (127.0.0.1) 81.43ms
[I 151209 15:06:49 autoreload:204] group_chat.py modified; restarting server
[I 151209 15:50:00 autoreload:204] group_chat.py modified; restarting server
[I 151209 15:52:15 web:1908] 200 GET /create_group?owner=919999823930&name=group4&members=[919811389321] (127.0.0.1) 84.97ms
[I 151209 15:53:13 web:1908] 200 GET /send_message?sender=919811389321&group_name=group4&message=heyi (127.0.0.1) 28.24ms
[I 151209 16:49:07 web:1908] 200 GET /create_group?owner=919999823930&name=grp1&members=[919811389321] (127.0.0.1) 97.71ms
[I 151209 16:51:07 web:1908] 200 GET /send_message?sender=919999823930&group_name=grp1&message=group1itis (127.0.0.1) 31.66ms
[I 151209 16:52:28 web:1908] 304 GET /send_message?sender=919999823930&group_name=grp1&message=group1itis (127.0.0.1) 29.55ms
[I 151209 16:54:33 web:1908] 200 GET /send_message?sender=919999823930&group_name=grp1&message=HEHEHEHEHEH (127.0.0.1) 30.26ms
[I 151209 16:55:42 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151209 16:56:00 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151209 16:59:04 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151209 17:01:53 web:1908] 304 GET /send_message?sender=919999823930&group_name=grp1&message=HEHEHEHEHEH (127.0.0.1) 28.08ms
[I 151209 17:13:39 web:1908] 200 GET /create_group?owner=916543789203&name=group8&members=[910987654321] (127.0.0.1) 10.29ms
[I 151209 17:14:11 web:1908] 200 GET /create_group?owner=916543789203&name=group8&members=[910987654321] (127.0.0.1) 69.60ms
[I 151209 17:14:46 web:1908] 200 GET /send_message?sender=916543789203&group_name=group8&message=how (127.0.0.1) 31.58ms
[I 151209 17:42:38 web:1908] 200 GET /create_group?owner=client1&name=group1&members=[client2,client3] (127.0.0.1) 9.89ms
[I 151209 17:42:53 autoreload:204] group_chat.py modified; restarting server
[I 151209 17:42:58 web:1908] 200 GET /create_group?owner=client1&name=group1&members=[client2,client3] (127.0.0.1) 11.45ms
[I 151209 17:43:50 autoreload:204] group_chat.py modified; restarting server
[I 151209 17:43:54 web:1908] 200 GET /create_group?owner=client1&name=group1&members=[client2,client3] (127.0.0.1) 87.66ms
[I 151209 17:44:46 web:1908] 200 GET /send_message?sender=client2&group_name=group1&message=hello1 (127.0.0.1) 26.08ms
[I 151209 18:15:26 web:1908] 304 GET /send_message?sender=client2&group_name=group1&message=hello1 (127.0.0.1) 31.05ms
[I 151209 18:18:27 web:1908] 304 GET /send_message?sender=client2&group_name=group1&message=hello1 (127.0.0.1) 30.78ms
[I 151209 18:31:13 web:1908] 304 GET /send_message?sender=client2&group_name=group1&message=hello1 (127.0.0.1) 28.86ms
[I 151209 18:48:51 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151209 18:49:36 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151209 18:51:32 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151209 18:51:52 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151210 06:24:41 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151210 06:27:06 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151210 06:29:45 web:1908] 200 GET /create_group?owner=client4&name=g1&members=[client2] (127.0.0.1) 70.42ms
[I 151210 06:32:07 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 06:33:03 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 06:33:29 web:1908] 304 GET /create_group?owner=client4&name=g1&members=[client2] (127.0.0.1) 78.52ms
[I 151210 06:34:37 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 06:35:11 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 06:35:27 web:1908] 304 GET /create_group?owner=client4&name=g1&members=[client2] (127.0.0.1) 71.28ms
[I 151210 06:36:19 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 06:36:34 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 06:36:37 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 06:36:51 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 06:36:58 web:1908] 200 GET /create_group?owner=client4&name=g1&members=[client2] (127.0.0.1) 27.01ms
[I 151210 06:37:09 web:1908] 200 GET /create_group?owner=client4&name=g1&members=[client2] (127.0.0.1) 177.49ms
[I 151210 06:38:25 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151210 06:40:40 web:1908] 304 GET /create_group?owner=client4&name=g1&members=[client2] (127.0.0.1) 59.83ms
[I 151210 06:41:47 web:1908] 200 GET /send_message?sender=client4&group_name=g1&message=msg1 (127.0.0.1) 27.45ms
[I 151210 06:42:39 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151210 06:43:57 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/publisher.py modified; restarting server
[I 151210 06:45:00 web:1908] 304 GET /send_message?sender=client4&group_name=g1&message=msg1 (127.0.0.1) 34.09ms
[I 151210 06:45:30 web:1908] 200 GET /send_message?sender=client3&group_name=g1&message=msg1 (127.0.0.1) 21.32ms
[I 151210 06:46:36 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/errors.py modified; restarting server
[I 151210 06:46:41 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/errors.py modified; restarting server
[I 151210 06:46:51 autoreload:204] group_chat.py modified; restarting server
[I 151210 06:48:18 web:1908] 200 GET /create_group?owner=client3&name=g2&members=[client1] (127.0.0.1) 85.64ms
[I 151210 06:49:15 web:1908] 200 GET /send_message?sender=client3&group_name=g2&message=message1 (127.0.0.1) 25.94ms
[I 151210 06:56:36 web:1908] 200 GET /create_group?owner=client3&name=g3&members=[client1] (127.0.0.1) 69.21ms
[I 151210 07:05:34 web:1908] 200 GET /create_group?owner=client5&name=grp4&members=[client6] (127.0.0.1) 75.32ms
[I 151210 07:06:30 web:1908] 200 GET /send_message?sender=client2&group_name=grp41&message=message1 (127.0.0.1) 18.47ms
[I 151210 07:06:39 web:1908] 200 GET /send_message?sender=client6&group_name=grp41&message=message1 (127.0.0.1) 17.91ms
[I 151210 07:06:53 web:1908] 200 GET /send_message?sender=client6&group_name=grp4&message=message1 (127.0.0.1) 30.07ms
[I 151210 07:07:58 web:1908] 200 GET /send_message?sender=client5&group_name=grp4&message=message2 (127.0.0.1) 26.62ms
[I 151210 07:11:57 web:1908] 200 GET /create_group?owner=c1&name=g1&members=[c2] (127.0.0.1) 75.83ms
[I 151210 07:12:32 web:1908] 200 GET /send_message?sender=c2&group_name=g1&message=h1 (127.0.0.1) 25.83ms
[I 151210 07:14:13 web:1908] 200 GET /send_message?sender=c1&group_name=g1&message=h2 (127.0.0.1) 26.55ms
[I 151210 07:14:46 web:1908] 200 GET /send_message?sender=c1&group_name=g1&message=h3 (127.0.0.1) 34.15ms
[I 151210 07:14:59 web:1908] 200 GET /send_message?sender=c2&group_name=g1&message=h4 (127.0.0.1) 29.90ms
[I 151210 07:16:22 web:1908] 200 GET /create_group?owner=c3&name=g2&members=[c4,c5] (127.0.0.1) 89.40ms
[I 151210 07:17:04 web:1908] 200 GET /send_message?sender=c4&group_name=g2&message=msg1 (127.0.0.1) 32.09ms
[I 151210 07:17:25 web:1908] 200 GET /send_message?sender=c5&group_name=g2&message=msg2 (127.0.0.1) 32.56ms
[I 151210 07:17:35 web:1908] 200 GET /send_message?sender=c3&group_name=g2&message=msg3 (127.0.0.1) 27.33ms
[I 151210 07:17:46 web:1908] 200 GET /send_message?sender=c4&group_name=g2&message=msg4 (127.0.0.1) 39.99ms
[I 151210 07:18:31 web:1908] 200 GET /create_group?owner=c2&name=g3&members=[c3,c5] (127.0.0.1) 88.62ms
[I 151210 07:19:00 web:1908] 200 GET /send_message?sender=c3&group_name=g3&message=hehe1 (127.0.0.1) 28.32ms
[I 151210 07:19:18 web:1908] 200 GET /send_message?sender=c2&group_name=g3&message=hehe2 (127.0.0.1) 27.21ms
[I 151210 07:19:48 web:1908] 200 GET /send_message?sender=c5&group_name=g3&message=hehe3 (127.0.0.1) 34.18ms
[I 151210 07:20:25 web:1908] 200 GET /send_message?sender=c5&group_name=g3&message=hehe4 (127.0.0.1) 39.83ms
[I 151210 07:20:44 web:1908] 200 GET /send_message?sender=c5&group_name=g3&message=hehe5 (127.0.0.1) 29.44ms
[I 151210 07:35:59 web:1908] 200 GET /send_message?sender=c1&group_name=g1&message=hehe5 (127.0.0.1) 26.32ms
[I 151210 07:42:56 web:1908] 200 GET /send_message?sender=c1&group_name=g1&message=hehe6 (127.0.0.1) 38.52ms
[I 151210 07:43:45 web:1908] 200 GET /send_message?sender=c1&group_name=g1&message=hehe7 (127.0.0.1) 34.95ms
[I 151210 08:28:39 web:1908] 200 GET /send_message?sender=c2&group_name=g3&message=hehe6 (127.0.0.1) 28.08ms
[I 151210 08:29:31 web:1908] 200 GET /create_group?owner=c1&name=g5&members=[c2,c3] (127.0.0.1) 88.90ms
[I 151210 08:30:16 web:1908] 200 GET /send_message?sender=c3&group_name=g5&message=heqqqq1 (127.0.0.1) 29.57ms
[I 151210 08:31:34 web:1908] 200 GET /create_group?owner=c5&name=group1&members=[c4] (127.0.0.1) 66.02ms
[I 151210 08:34:08 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 08:34:33 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 08:35:09 web:1908] 200 GET /create_group?owner=c5&name=group1&members=[c4] (127.0.0.1) 23.61ms
[I 151210 08:35:19 web:1908] 200 GET /create_group?owner=c5&name=g10&members=[c4] (127.0.0.1) 69.14ms
[I 151210 08:35:49 web:1908] 200 GET /send_message?sender=c4&group_name=g10&message=h1 (127.0.0.1) 30.83ms
[I 151210 08:37:48 autoreload:204] /home/mama20/Documents/sportsUnity/group_chat/subscriber.py modified; restarting server
[I 151210 11:21:14 web:1908] 200 GET /send_message?sender=c4&group_name=g10&message=h2 (127.0.0.1) 28.82ms
[I 151210 11:22:31 web:1908] 200 GET /create_group?owner=c4&name=g6&members=[c1,c3] (127.0.0.1) 82.27ms
[I 151210 11:23:04 web:1908] 200 GET /send_message?sender=c1&group_name=g6&message=hie1 (127.0.0.1) 31.67ms
[I 151210 11:31:18 web:1908] 200 GET /create_group?owner=c1&name=group1&members=[c2,c3] (127.0.0.1) 85.01ms
[I 151210 11:31:41 web:1908] 304 GET /create_group?owner=c1&name=group1&members=[c2,c3] (127.0.0.1) 77.83ms
[I 151210 11:32:25 web:1908] 200 GET /send_message?sender=c2&group_name=group1&message=msg1 (127.0.0.1) 30.67ms
[I 151210 11:33:03 web:1908] 200 GET /send_message?sender=c4&group_name=group1&message=msg2 (127.0.0.1) 17.75ms
[I 151210 11:33:06 web:1908] 200 GET /send_message?sender=c3&group_name=group1&message=msg2 (127.0.0.1) 26.21ms
[I 151210 11:33:41 web:1908] 200 GET /create_group?owner=919999823930&name=group2&members=[919716671667] (127.0.0.1) 69.47ms
[I 151210 11:34:16 web:1908] 200 GET /send_message?sender=919999823930&group_name=group2&message=msg3 (127.0.0.1) 26.42ms
[I 151210 11:34:44 web:1908] 200 GET /send_message?sender=919716671667&group_name=group2&message=msg4 (127.0.0.1) 37.12ms
[I 151210 11:37:37 web:1908] 200 GET /send_message?sender=919716671667&group_name=group2&message=msg5 (127.0.0.1) 29.28ms
[I 151211 14:09:34 autoreload:204] /home/mama20/Documents/MQTT/group_chat/publisher.py modified; restarting server
[I 151214 16:07:05 web:1908] 200 GET /call_method (127.0.0.1) 0.72ms
[E 151214 16:07:21 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 289, in get
        CreateGroup.get(args, kwargs)
    TypeError: unbound method get() must be called with CreateGroup instance as first argument (got tuple instance instead)
[E 151214 16:07:21 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 36.38ms
[I 151214 16:08:05 autoreload:204] group_chat.py modified; restarting server
[E 151214 16:08:11 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Cache-Control': 'max-age=0', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 289, in get
        CreateGroup().get(args, kwargs)
    TypeError: __init__() takes exactly 3 arguments (1 given)
[E 151214 16:08:11 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 2.37ms
[I 151214 16:08:32 autoreload:204] group_chat.py modified; restarting server
[E 151214 16:08:37 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Cache-Control': 'max-age=0', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 289, in get
        CreateGroup.get(self, args, kwargs)
    TypeError: unbound method get() must be called with CreateGroup instance as first argument (got callMethod instance instead)
[E 151214 16:08:37 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 2.31ms
[I 151214 16:08:57 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:09:04 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:09:52 autoreload:204] /home/mama20/Documents/MQTT/group_chat/settings.py modified; restarting server
[I 151214 16:10:21 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:10:31 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:10:32 autoreload:204] group_chat.py modified; restarting server
[E 151214 16:12:10 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 289, in get
        request.get('http://' + SERVER_IP + ':' + SERVER_PORT + '/create_group', data=kwargs)
    NameError: global name 'request' is not defined
[E 151214 16:12:10 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 2.56ms
[I 151214 16:13:00 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:13:05 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:13:20 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:13:36 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:13:42 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:14:16 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:14:58 autoreload:204] group_chat.py modified; restarting server
[E 151214 16:15:06 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 289, in get
        request.get('http://' + SERVER_IP + ':' + SERVER_PORT + '/create_group',
    NameError: global name 'request' is not defined
[E 151214 16:15:06 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 1.66ms
[I 151214 16:15:14 autoreload:204] group_chat.py modified; restarting server
[E 151214 16:15:22 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Cache-Control': 'max-age=0', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 289, in get
        requests.get('http://' + SERVER_IP + ':' + SERVER_PORT + '/create_group',
    TypeError: cannot concatenate 'str' and 'int' objects
[E 151214 16:15:22 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 4.51ms
[I 151214 16:15:41 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:15:49 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:18:58 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 291, in get
        'members': self.get_argument('members', '')})
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[I 151214 16:18:58 web:1908] 200 GET /create_group (127.0.0.1) 1.12ms
[I 151214 16:18:58 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:19:17 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 291, in get
        'members': self.get_argument('members', '')})
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[I 151214 16:19:17 web:1908] 200 GET /create_group (127.0.0.1) 0.86ms
[I 151214 16:19:30 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:24:48 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 291, in get
        #             data={'owner': self.get_argument('owner', ''), 'name': self.get_argument('owner', ''),
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[I 151214 16:24:48 web:1908] 200 GET /create_group (127.0.0.1) 1.01ms
[I 151214 16:24:48 autoreload:204] group_chat.py modified; restarting server
[E 151214 16:25:01 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 289, in get
        CreateGroup().get(args, kwargs)
    TypeError: __init__() takes exactly 3 arguments (1 given)
[E 151214 16:25:01 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 2.29ms
[I 151214 16:26:17 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:29:11 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:29:13 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:29:27 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:31:40 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:32:29 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 288, in get
        requests.get(url, data={'owner': self.get_argument('owner', ''), 'name': self.get_argument('name', ''),
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[I 151214 16:32:29 web:1908] 200 GET /create_group (127.0.0.1) 0.81ms
[I 151214 16:32:29 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:34:05 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 288, in get
        requests.post(url, data={'owner': self.get_argument('owner', ''), 'name': self.get_argument('name', ''),
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[I 151214 16:34:05 web:1908] 200 GET /create_group (127.0.0.1) 0.46ms
[I 151214 16:34:05 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:34:12 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 288, in get
        requests.post(url, data={'owner': self.get_argument('owner', ''), 'name': self.get_argument('name', ''),
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
        return request('get', url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[I 151214 16:34:12 web:1908] 200 GET /create_group (127.0.0.1) 1.98ms
[I 151214 16:34:12 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:34:28 web:1908] 200 GET /call_method?method=CreateGroup?owner=1 (127.0.0.1) 0.83ms
[I 151214 16:35:16 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:35:25 web:1908] 304 GET /call_method?method=CreateGroup?owner=1 (127.0.0.1) 0.66ms
[I 151214 16:36:53 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:38:07 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 290, in get
        'members': self.get_argument('members', '')})
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
        return request('post', url, data=data, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[I 151214 16:38:07 web:1908] 200 POST /create_group (127.0.0.1) 0.45ms
[I 151214 16:38:07 autoreload:204] group_chat.py modified; restarting server
[E 151214 16:38:21 web:1496] Uncaught exception GET /call_method?method=CreateGroup&owner=1 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup&owner=1', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 290, in get
        'members': self.get_argument('members', '')})
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
        return request('post', url, data=data, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 421, in request
        prep = self.prepare_request(req)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 359, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "/usr/lib/python2.7/dist-packages/requests/models.py", line 287, in prepare
        self.prepare_url(url, params)
      File "/usr/lib/python2.7/dist-packages/requests/models.py", line 338, in prepare_url
        "Perhaps you meant http://{0}?".format(url))
    MissingSchema: Invalid URL u'/create_group': No schema supplied. Perhaps you meant http:///create_group?
[E 151214 16:38:21 web:1908] 500 GET /call_method?method=CreateGroup&owner=1 (127.0.0.1) 16.56ms
[I 151214 16:38:37 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:40:00 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:40:15 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:55:51 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 290, in get
        #     url = 'http://localhost:3000/create_group'
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
        return request('post', url, data=data, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[I 151214 16:55:51 web:1908] 200 POST /create_group (127.0.0.1) 0.57ms
[I 151214 16:55:51 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 16:55:55 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 290, in get
        #     url = 'http://localhost:3000/create_group'
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
        return request('post', url, data=data, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[W 151214 16:55:55 web:1908] 405 GET /create_group (127.0.0.1) 0.59ms
[I 151214 16:55:55 web:1908] 200 POST /create_group (127.0.0.1) 0.41ms
[I 151214 16:55:55 autoreload:204] group_chat.py modified; restarting server
[I 151214 16:56:55 web:1908] 200 GET /create_group?owner=c1&name=group1&members=[c2,c3] (127.0.0.1) 1.36ms
[I 151214 17:03:54 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:04:14 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:07:09 web:1908] 304 GET /create_group?owner=c1&name=group1&members=[c2,c3] (127.0.0.1) 1.76ms
[I 151214 17:08:10 autoreload:204] group_chat.py modified; restarting server
[W 151214 17:15:52 web:1908] 404 GET /call_method?method=CreateGroup (127.0.0.1) 0.99ms
[I 151214 17:16:01 autoreload:204] group_chat.py modified; restarting server
[E 151214 17:16:04 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 308, in get
        client = tornado.httpclient.HTTPClient()
    AttributeError: 'module' object has no attribute 'httpclient'
[E 151214 17:16:04 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 1.63ms
[I 151214 17:16:44 autoreload:204] group_chat.py modified; restarting server
[E 151214 17:16:51 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 313, in get
        body = urllib.urlencode({'owner': self.get_argument('owner', ''), 'name': self.get_argument('name', ''),
    NameError: global name 'urllib' is not defined
[E 151214 17:16:51 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 2.92ms
[I 151214 17:17:15 autoreload:204] group_chat.py modified; restarting server
[E 151214 17:17:22 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 318, in get
        res = client.fetch(req)
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch
        self._async_client.fetch, request, **kwargs))
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync
        return future_cell[0].result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    ValueError: Body must be None for method GET (unless allow_nonstandard_methods is true)
[E 151214 17:17:22 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 55.18ms
[I 151214 17:18:08 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:18:16 autoreload:204] group_chat.py modified; restarting server
[E 151214 17:18:41 web:1496] Uncaught exception GET /call_method?method=CreateGroup (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 318, in get
        res = client.fetch(req)
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch
        self._async_client.fetch, request, **kwargs))
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync
        return future_cell[0].result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    HTTPError: HTTP 599: Timeout
[E 151214 17:18:41 web:1908] 500 GET /call_method?method=CreateGroup (127.0.0.1) 20024.70ms
[I 151214 17:18:41 web:1908] 200 POST /create_group (127.0.0.1) 1.59ms
[I 151214 17:19:32 web:1908] 200 GET /call_method?method=CreateGroup?owner=a (127.0.0.1) 0.67ms
[I 151214 17:20:07 web:1908] 304 GET /call_method?method=CreateGroup?owner=a (127.0.0.1) 2.19ms
[E 151214 17:21:02 web:1496] Uncaught exception GET /call_method?method=CreateGroup&owner=a (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/call_method?method=CreateGroup&owner=a', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 318, in get
        res = client.fetch(req)
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch
        self._async_client.fetch, request, **kwargs))
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync
        return future_cell[0].result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    HTTPError: HTTP 599: Timeout
[E 151214 17:21:02 web:1908] 500 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 20023.92ms
[I 151214 17:21:02 web:1908] 200 POST /create_group (127.0.0.1) 1.08ms
[I 151214 17:22:20 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:22:25 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:22:50 web:1908] 200 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 20013.63ms
[I 151214 17:22:50 web:1908] 200 POST /create_group (127.0.0.1) 1.60ms
[I 151214 17:23:32 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:24:36 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:24:45 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:25:10 web:1908] 304 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 20010.19ms
[I 151214 17:25:10 web:1908] 200 POST /create_group (127.0.0.1) 0.83ms
[I 151214 17:32:08 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:32:29 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:32:55 web:1908] 304 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 20015.42ms
[E 151214 17:32:55 web:1496] Uncaught exception POST /create_group (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='POST', uri='/create_group', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '22', 'Connection': 'close', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'localhost:3000', 'Accept-Encoding': 'gzip'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1417, in _execute
        raise TypeError("Expected None, got %r" % result)
    TypeError: Expected None, got {'info': ' Bad Request: Please provide a valid phone number of group owner!', 'status': 400}
[E 151214 17:32:55 web:1908] 500 POST /create_group (127.0.0.1) 2.11ms
[I 151214 17:55:43 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:56:10 web:1908] 304 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 20022.06ms
[E 151214 17:56:10 web:1496] Uncaught exception POST /create_group (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='POST', uri='/create_group', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '22', 'Connection': 'close', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'localhost:3000', 'Accept-Encoding': 'gzip'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1417, in _execute
        raise TypeError("Expected None, got %r" % result)
    TypeError: Expected None, got {'info': ' Bad Request: Please provide a valid phone number of group owner!', 'status': 400}
[E 151214 17:56:10 web:1908] 500 POST /create_group (127.0.0.1) 2.12ms
[I 151214 17:56:45 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:57:09 web:1908] 304 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 20022.76ms
[E 151214 17:57:09 web:1496] Uncaught exception POST /create_group (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='POST', uri='/create_group', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '22', 'Connection': 'close', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'localhost:3000', 'Accept-Encoding': 'gzip'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1417, in _execute
        raise TypeError("Expected None, got %r" % result)
    TypeError: Expected None, got {'info': ' Bad Request: Please provide a valid phone number of group owner!', 'status': 400}
[E 151214 17:57:09 web:1908] 500 POST /create_group (127.0.0.1) 3.44ms
[I 151214 17:57:16 autoreload:204] group_chat.py modified; restarting server
[I 151214 17:59:17 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:00:34 web:1908] 304 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 1.70ms
[I 151214 18:01:10 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:02:48 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:03:07 web:1908] 304 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 3.08ms
[I 151214 18:03:43 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:04:09 web:1908] 304 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 20022.70ms
[E 151214 18:04:09 web:1496] Uncaught exception POST /create_group (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='POST', uri='/create_group', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Content-Length': '22', 'Connection': 'close', 'Content-Type': 'application/x-www-form-urlencoded', 'Host': 'localhost:3000', 'Accept-Encoding': 'gzip'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1417, in _execute
        raise TypeError("Expected None, got %r" % result)
    TypeError: Expected None, got {'info': ' Bad Request: Please provide a valid phone number of group owner!', 'status': 400}
[E 151214 18:04:09 web:1908] 500 POST /create_group (127.0.0.1) 2.06ms
[I 151214 18:15:56 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:16:24 web:1908] 304 GET /call_method?method=CreateGroup&owner=a (127.0.0.1) 20022.58ms
[E 151214 18:16:24 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 185, in _read_message
        header_future = delegate.headers_received(start_line, headers)
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 276, in headers_received
        return self.delegate.headers_received(start_line, headers)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1925, in headers_received
        headers=headers))
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1933, in set_request
        self.stream_request_body = _has_stream_request_body(self.handler_class)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1625, in _has_stream_request_body
        raise TypeError("expected subclass of RequestHandler, got %r", cls)
    TypeError: ('expected subclass of RequestHandler, got %r', <class '__main__.CreateGroup'>)
[E 151214 18:16:24 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 259, in _read_message
        delegate.on_connection_close()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 297, in on_connection_close
        self.delegate.on_connection_close()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1987, in on_connection_close
        if self.stream_request_body:
    AttributeError: '_RequestDispatcher' object has no attribute 'stream_request_body'
[I 151214 18:17:13 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:17:45 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:19:13 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:19:36 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:19:45 autoreload:204] group_chat.py modified; restarting server
[I 151214 18:20:15 connectionpool:259] Starting new HTTP connection (1): localhost
[E 151214 18:21:21 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 238, in _read_message
        delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 290, in finish
        self.delegate.finish()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1984, in finish
        self.execute()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2017, in execute
        **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 292, in get
        res = requests.post('http://localhost:3000/create_group', data=data)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
        return request('post', url, data=data, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
        return session.request(method=method, url=url, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
        r = adapter.send(request, **kwargs)
      File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 330, in send
        timeout=timeout
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
        body=body, headers=headers)
      File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 409, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
        response.begin()
      File "/usr/lib/python2.7/httplib.py", line 415, in begin
        version, status, reason = self._read_status()
      File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/usr/lib/python2.7/socket.py", line 476, in readline
        data = self._sock.recv(self._rbufsize)
    KeyboardInterrupt
[E 151214 18:21:21 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 185, in _read_message
        header_future = delegate.headers_received(start_line, headers)
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 276, in headers_received
        return self.delegate.headers_received(start_line, headers)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1925, in headers_received
        headers=headers))
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1933, in set_request
        self.stream_request_body = _has_stream_request_body(self.handler_class)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1625, in _has_stream_request_body
        raise TypeError("expected subclass of RequestHandler, got %r", cls)
    TypeError: ('expected subclass of RequestHandler, got %r', <class '__main__.CreateGroup'>)
[E 151214 18:21:21 http1connection:54] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 259, in _read_message
        delegate.on_connection_close()
      File "/usr/local/lib/python2.7/dist-packages/tornado/httpserver.py", line 297, in on_connection_close
        self.delegate.on_connection_close()
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1987, in on_connection_close
        if self.stream_request_body:
    AttributeError: '_RequestDispatcher' object has no attribute 'stream_request_body'
[I 151214 18:21:21 autoreload:204] group_chat.py modified; restarting server
[I 151215 15:27:54 autoreload:204] group_chat.py modified; restarting server
[I 151215 15:28:02 autoreload:204] group_chat.py modified; restarting server
[I 151215 15:28:26 autoreload:204] group_chat.py modified; restarting server
[I 151215 15:45:51 web:1908] 200 GET /start_stop_app (127.0.0.1) 0.95ms
[E 151215 15:46:11 web:1496] Uncaught exception GET /start_stop_app?user=717818 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=717818', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 392, in get
        res =  self.data_validation(user, contacts)
      File "group_chat.py", line 359, in data_validation
        if len(owner) != 12:
    NameError: global name 'owner' is not defined
[E 151215 15:46:11 web:1908] 500 GET /start_stop_app?user=717818 (127.0.0.1) 2.66ms
[I 151215 15:46:21 autoreload:204] group_chat.py modified; restarting server
[I 151215 15:46:27 web:1908] 200 GET /start_stop_app?user=717818 (127.0.0.1) 0.74ms
[I 151215 15:49:55 web:1908] 200 GET /start_stop_app?user=919876543213 (127.0.0.1) 10.71ms
[I 151215 15:50:31 autoreload:204] group_chat.py modified; restarting server
[E 151215 15:50:35 web:1496] Uncaught exception GET /start_stop_app?user=919876543213 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919876543213', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'If-None-Match': '"0ec71684e8d92d90e5d90cb1df3a3ade59b283a9"', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 393, in get
        return self.write(res)
    UnboundLocalError: local variable 'res' referenced before assignment
[E 151215 15:50:35 web:1908] 500 GET /start_stop_app?user=919876543213 (127.0.0.1) 4.78ms
[I 151215 15:51:24 autoreload:204] group_chat.py modified; restarting server
[I 151215 15:51:26 web:1908] 200 GET /start_stop_app?user=919876543213 (127.0.0.1) 0.67ms
[I 151215 15:51:37 web:1908] 200 GET /start_stop_app? (127.0.0.1) 0.35ms
[I 151215 15:51:39 web:1908] 200 GET /start_stop_app (127.0.0.1) 0.41ms
[W 151215 15:51:43 web:1908] 404 GET / (127.0.0.1) 0.31ms
[I 151215 15:51:48 web:1908] 304 GET /start_stop_app (127.0.0.1) 0.48ms
[I 151215 15:52:00 web:1908] 200 GET /start_stop_app?user=919876543213&event=start (127.0.0.1) 9.76ms
[E 151215 15:52:46 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 407, in get
        self.publish_presence_notification(client_id, user_data)
    TypeError: publish_presence_notification() takes exactly 2 arguments (3 given)
[E 151215 15:52:46 web:1908] 500 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 14.17ms
[I 151215 15:53:18 autoreload:204] group_chat.py modified; restarting server
[E 151215 15:53:25 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 414, in get
        self.subscribe_contacts_presence(client_id, user_data)  ## will be a frontend function
    TypeError: subscribe_contacts_presence() takes exactly 2 arguments (3 given)
[E 151215 15:53:25 web:1908] 500 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 11.29ms
[I 151215 15:53:43 autoreload:204] group_chat.py modified; restarting server
[E 151215 15:53:58 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 423, in get
        friends_status[friend] = result[0]['status']
    IndexError: list index out of range
[E 151215 15:53:58 web:1908] 500 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 21.95ms
[I 151215 15:59:31 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:00:05 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:00:09 autoreload:204] group_chat.py modified; restarting server
[E 151215 16:00:16 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 424, in get
        friends_status[friend] = result[0]['status']
    IndexError: list index out of range
[E 151215 16:00:16 web:1908] 500 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 20.32ms
[I 151215 16:00:54 autoreload:204] group_chat.py modified; restarting server
[E 151215 16:01:02 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 425, in get
        friends_status[friend] = result[0]['status']
    IndexError: list index out of range
[E 151215 16:01:02 web:1908] 500 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 21.87ms
[I 151215 16:01:45 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:01:52 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:01:54 web:1908] 200 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 22.19ms
[I 151215 16:02:04 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:02:18 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:02:25 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:02:34 web:1908] 200 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 10.73ms
[I 151215 16:04:12 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:04:27 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:04:59 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:05:04 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:05:16 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:05:21 autoreload:204] /home/mama20/Documents/MQTT/group_chat/errors.py modified; restarting server
[I 151215 16:05:31 autoreload:204] /home/mama20/Documents/MQTT/group_chat/errors.py modified; restarting server
[I 151215 16:05:32 autoreload:204] /home/mama20/Documents/MQTT/group_chat/errors.py modified; restarting server
[I 151215 16:09:45 autoreload:204] group_chat.py modified; restarting server
[E 151215 16:28:33 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'If-None-Match': '"bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f"', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 398, in get
        res =  self.data_validation(user, event, contacts)
    TypeError: data_validation() takes exactly 3 arguments (4 given)
[E 151215 16:28:33 web:1908] 500 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 1.58ms
[I 151215 16:28:49 autoreload:204] group_chat.py modified; restarting server
[E 151215 16:28:58 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 404, in get
        print 'TOPIC:', topic
    NameError: global name 'topic' is not defined
[E 151215 16:28:58 web:1908] 500 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 14.20ms
[I 151215 16:29:11 autoreload:204] group_chat.py modified; restarting server
[I 151215 16:29:16 web:1908] 200 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 10.65ms
[I 151215 16:33:07 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:33:24 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:33:54 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:34:16 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:34:41 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:35:33 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:35:41 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:36:03 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:36:42 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:37:14 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:37:40 autoreload:204] /usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py modified; restarting server
[I 151215 16:37:54 web:1908] 304 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 13.28ms
[E 151215 16:58:54 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'If-None-Match': '"bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f"', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 337, in get
        publish_presence_notification(client_id, user_data)
      File "/home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py", line 32, in publish_presence_notification
        client.on_connect = self.on_connect
    NameError: global name 'self' is not defined
[E 151215 16:58:54 web:1908] 500 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 11.37ms
[I 151215 16:59:22 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151215 16:59:36 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151215 16:59:45 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151215 16:59:51 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151215 17:00:00 web:1908] 200 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 13.53ms
[I 151215 17:17:06 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:17:41 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:18:05 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:21:58 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:22:14 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:22:16 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:22:23 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:24:01 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:25:17 autoreload:204] group_chat.py modified; restarting server
[I 151215 17:27:59 web:1908] 304 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 10.90ms
[I 151215 17:28:57 web:1908] 200 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 11.49ms
[I 151215 17:34:19 web:1908] 304 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 9.39ms
[I 151215 18:10:42 autoreload:204] group_chat.py modified; restarting server
[I 151215 18:14:27 autoreload:204] group_chat.py modified; restarting server
[I 151215 18:16:12 web:1908] 304 GET /start_stop_app?user=919999823930&event=start (127.0.0.1) 14.08ms
[I 151215 18:17:13 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 9.95ms
[I 151215 18:17:47 web:1908] 200 GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1) 22.45ms
[I 151215 18:18:17 autoreload:204] group_chat.py modified; restarting server
[I 151215 18:18:22 web:1908] 200 GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1) 25.38ms
[I 151216 11:13:22 web:1908] 200 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 21.60ms
[I 151216 11:14:01 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:14:15 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 20.22ms
[I 151216 11:15:00 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:15:07 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 19.23ms
[I 151216 11:15:22 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:16:24 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:16:30 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 19.12ms
[I 151216 11:17:28 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:17:32 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 17.85ms
[I 151216 11:18:24 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 17.32ms
[I 151216 11:19:00 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:19:34 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 18.34ms
[I 151216 11:19:57 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:20:16 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:20:23 web:1908] 200 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 13.45ms
[I 151216 11:23:36 web:1908] 304 GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1) 17.46ms
[I 151216 11:24:36 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:24:44 web:1908] 304 GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1) 22.26ms
[I 151216 11:25:52 autoreload:204] group_chat.py modified; restarting server
[I 151216 11:26:05 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 14.85ms
[E 151216 11:28:40 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start&contacts=[919811389321]', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'If-None-Match': '"bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f"', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 352, in get
        subscribe_contacts_presence(client_id, user_data)  ## will be a frontend function
    TypeError: subscribe_contacts_presence() takes exactly 3 arguments (2 given)
[E 151216 11:28:40 web:1908] 500 GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1) 19.74ms
[I 151216 11:29:11 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 11:29:14 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 11:30:20 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 10.87ms
[E 151216 11:30:38 web:1496] Uncaught exception GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:3000', method='GET', uri='/start_stop_app?user=919999823930&event=start&contacts=[919811389321]', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Host': 'localhost:3000', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:41.0) Gecko/20100101 Firefox/41.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1413, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "group_chat.py", line 352, in get
        subscribe_contacts_presence(client_id, user_data)  ## will be a frontend function
      File "/home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py", line 68, in subscribe_contacts_presence
        client.on_connect = self.on_subscriber_connect
    NameError: global name 'self' is not defined
[E 151216 11:30:38 web:1908] 500 GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1) 24.07ms
[I 151216 11:30:54 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 11:31:34 web:1908] 304 GET /start_stop_app?user=919999823930&event=stop (127.0.0.1) 11.08ms
[I 151216 11:31:39 web:1908] 200 GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1) 37.86ms
[I 151216 11:31:56 web:1908] 200 GET /start_stop_app?user=919811389321&event=start (127.0.0.1) 13.34ms
[I 151216 11:32:12 web:1908] 200 GET /start_stop_app?user=919999823930&event=start&contacts=[919811389321] (127.0.0.1) 31.37ms
[I 151216 11:32:20 web:1908] 200 GET /start_stop_app?user=919999823930&event=stop&contacts=[919811389321] (127.0.0.1) 26.83ms
[I 151216 11:37:07 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 11:40:25 web:1908] 200 GET /start_stop_app?user=919999823930&event=start&contacts=[919958776104] (127.0.0.1) 33.01ms
[I 151216 12:19:58 web:1908] 200 GET /start_stop_app?user=919876543210&event=stop (127.0.0.1) 10.51ms
[I 151216 12:20:36 web:1908] 200 GET /start_stop_app?user=919876543210&event=stop&contacts=[918765432109] (127.0.0.1) 28.38ms
[I 151216 12:29:39 web:1908] 200 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 36.36ms
[I 151216 13:40:13 web:1908] 304 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 30.90ms
[I 151216 13:41:17 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:41:25 web:1908] 304 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 27.57ms
[I 151216 13:42:09 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:42:19 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:42:23 web:1908] 304 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 28.64ms
[I 151216 13:42:41 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:42:48 web:1908] 304 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 30.28ms
[I 151216 13:52:43 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:52:56 web:1908] 304 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 34.24ms
[I 151216 13:53:21 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:53:28 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:53:55 web:1908] 304 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 40.89ms
[I 151216 13:54:05 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:54:12 web:1908] 304 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 34.79ms
[I 151216 13:56:42 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:57:27 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:57:30 autoreload:204] /home/mama20/Documents/MQTT/group_chat/utils/presence_notification.py modified; restarting server
[I 151216 13:57:39 web:1908] 304 GET /start_stop_app?user=916543210987&event=start&contacts=[917654321098] (127.0.0.1) 30.44ms
